### ISSUE TITLE
codegen: closure passed to FnMut-bound runtime fn (streaming callbacks) produces invalid Rust

### ISSUE THREAD

**Issue by atzurody** [almide/almide#408]
## Summary

On almide v0.24.0 and v0.25.0, generating code that passes a closure to a
runtime function bound as `impl FnMut(String)` (the streaming-callback shape)
produces invalid Rust. This breaks all streaming LLM calls, including the
stdlib's own `http.anthropic_streaming_call` / `http.openai_streaming_call`,
and makes `almide-ai/almai` impossible to compile.

## Repro (stdlib, no external deps)

`src/main.almd`:

```almide
import http
import env

effect fn main() -> Unit = {
  let key = env.get("ANTHROPIC_API_KEY") ?? ""
  var acc = ""
  let body = "{\"model\":\"claude-haiku-4-5\",\"max_tokens\":64,\"messages\":[{\"role\":\"user\",\"content\":\"hi\"}]}"
  let r = http.anthropic_streaming_call(key, body, (delta) => { acc = acc + delta })!
  println(acc)
}
```

```
$ almide build src/main.almd -o build/llm
error[E0277]: expected a `FnMut(String)` closure, found `Rc<dyn Fn(String)>`
  ... required by a bound in `almide_rt_sse_anthropic_messages`
  help: you might have meant to create the closure instead of a block
        let r: String = (almide_rt_sse_anthropic_messages(&*key, &*body, |_| {
```

The generated code passes the callback as `Rc<dyn Fn(String)>` (or emits a
block instead of a closure) while the runtime helper expects `impl FnMut(String)`.

## Impact

- Non-streaming `http.request` works fine on v0.25.
- Any streaming-callback path fails to compile (native + wasm).
- `almide-ai/almai` (last updated 2026-05-01) fails to compile on v0.24/v0.25
  for this reason, plus a secondary `error[E0599]: no method named almide_repr
  found for enum Value` from `Tool` deriving `Repr` with a `Value` field.

## Environment

- almide 0.25.0 (also reproduced on 0.24.0), prebuilt macOS aarch64 release
- rustc 1.96.0 (native fallback)

**Comment by atzurody** [comment]
Fix submitted in #409. Root causes: (1) the SSE runtime helpers (`almide_rt_sse_*`) took `impl FnMut(String)` while the uniform closure repr passes `Rc<dyn Fn(String) -> ()>` — aligned them with the `Rc<dyn Fn>` convention used by list.map/fold; (2) `Value` lacked an `AlmideRepr` impl, so any type with a `Value` field deriving `Repr` (e.g. almai's `Tool`) failed with E0599 — added `impl AlmideRepr for Value`. Verified that the stdlib streaming repro and almide-ai/almai both build, and the spec suite (stdlib/lang/integration, 248 files) is green.

**Comment by O6lvl4** [comment]
Fixed on `develop` (3c0a81e7) via @atzurody's #409 — the SSE streaming callback now takes `Rc<dyn Fn(String)>` to match the codegen's closure repr, so a capturing closure passed to `http.openai_streaming_call(...)` compiles to valid Rust. Verified by build + full spec suite (native + wasm). Ships in the next release.
