### ISSUE TITLE
A list combinator whose init argument consumes the same list emits Rust that does not compile, where 0.62.0 cloned the receiver

### ISSUE THREAD

**Issue by O6lvl4** [almide/almide#2377]
`almide check` accepts the program; `almide build` fails with **`codegen produced invalid Rust — this is an Almide bug`** over rustc's `error[E0505]: cannot move out of 'xs' because it is borrowed`. **0.62.0 builds and runs the same source.**

Found by the 2026-09-20 07:56 `fuzz-nightly` campaign (run 35498209567, shard 2, seed 567971353073 index 78) — the night recorded 1 correctness finding and no tracking issue was opened, so this is it.

## Repro, four lines

```almide
fn main() -> Unit = {
  let xs: List[Bool] = [true]
  let r: Bool = list.fold(xs, list.is_empty(list.sort_by(xs, ((y) => 1))), ((a, b) => a))
  println("${r}")
}
```

```
almide check   -> exit 0
almide build   -> codegen produced invalid Rust — this is an Almide bug.
                  error[E0505]: cannot move out of `xs` because it is borrowed
0.62.0 build   -> Built
```

## The diff is one line of emitted Rust

```rust
// 0.62.0 — the receiver is CLONED, so `xs` is still available to the init argument
let r: bool = (xs.clone()).into_iter().fold(
    almide_rt_list_is_empty(&almide_rt_list_sort_by(xs, ...)), move |a, b| a);

// 0.63 — the receiver is BORROWED, and the init argument moves `xs` out from under it
let r: bool = (xs).iter().cloned().fold(
    almide_rt_list_is_empty(&almide_rt_list_sort_by(xs, ...)), |a, b| a);
```

Borrowing the receiver instead of cloning it is the right optimisation and is one of 0.63's headline changes. What it misses is that **a sibling argument of the same call can consume the receiver**, and in Rust the argument expressions are evaluated while the receiver's borrow is live. The decision is made per-receiver; the thing that invalidates it is in another argument.

## What is and is not required

Measured by reduction from the fuzzer's program, each row built and A/B'd against 0.62.0:

| | builds on 0.63? |
|---|---|
| `list.fold(xs, list.is_empty(list.sort_by(xs, f)), g)` | **no** |
| `list.fold(xs, list.is_empty(list.sort(xs)), g)` | yes |
| `list.fold(xs, list.length(list.sort(xs)), g)` | yes |
| `list.fold(xs, list.is_empty(list.scan(xs, 1, f)), g)` | **no** |
| same, with `xs = []` instead of `[true]` | **no** |

So the consuming call in the init must be one that **also takes a closure** (`sort_by`, `scan`) — `list.sort` alone is fine. Whether the list literal is empty does not matter, nor does the element type, nor whether the fold's callback captures anything. The original fuzzer program reached it through `list.fold` with an `if`-expression init; the `if` is not required.

## Why it is a release blocker

It is a **regression**: source that 0.62.0 compiles is refused at HEAD, and refused with a banner that tells the author to file a compiler bug — so the failure mode is "your working program stops building and blames the compiler", which is the worst one to ship. It is also the class the ownership certifier (#2231) exists to catch, and it was not caught, so the certifier's coverage is worth a look alongside the fix.

Not yet located in the passes. The shape `(xs).iter().cloned()` is the fused-source form, so `pass_stream_fusion.rs` and `pass_borrow_inference_ownership.rs` are where I would read first, but I have not confirmed which one decides it.

**Comment by O6lvl4** [comment]
Root cause and fix are in #2376.

`ChainSourceBorrowPass` strips the clone in front of a fused chain's source and iterates from a borrow. Its guard asked whether anything inside the chain **writes** the same variable — the doc comment even names "a fold seed" as a case it considered — but the seed is evaluated while the receiver's borrow is live, so a **move** in it conflicts exactly as a write does, and that half was never asked.

The predicate for the other half already existed: `pass_clone_interp::moves_var`, whose own doc calls it "the conflicting half of the E0505". Two passes needed one rule and only one had it, so the guard now shares that predicate rather than restating it.

Verified: the fuzzer's original program, the four-line reduction and every intermediate reducer all build and run, with output identical to 0.62.0 on each. The optimisation is intact where it belongs — a seed that does not mention the list still emits `(xs).iter().cloned()` with no clone, asserted on the emitted Rust rather than inferred from a build that merely succeeded.

One follow-up worth its own issue rather than this fix: in the guarded case the emitted form is `(xs.clone()).iter().cloned()`, where 0.62.0 emitted `(xs.clone()).into_iter()`. Both are correct; the new one clones the vector and then clones each element, which for a `List[String]` is real duplicated work. Rare shape, and not something to change while cutting a release.
