### ISSUE TITLE
native regression since 2062dd0c: comparing a string.chars element to a literal emits &String vs &str (bisected)

### ISSUE THREAD

**Issue by atzurody** [almide/almide#2188]
## Summary

Comparing an element of `string.chars(s)` against a string literal inside a `for` loop stopped
compiling on native. `v0.62.0` builds it; `develop` does not.

Bisected (`git bisect run`, 9 steps over the 141 commits in `v0.62.0..develop`):

```
2062dd0cf2de1fc5244b1c3564428a25835ff9ee is the first bad commit
  Fix native ownership, fan callbacks, and WASM decoder reclamation
```

## Repro

`src/main.almd` — this is the whole program:

```almide
fn has_digit(s: String) -> Bool = {
  var out = false
  for c in string.chars(s) {
    let hit = c >= "0" and c <= "9"
    if hit then {
      out = true
    } else ()
  }
  out
}

effect fn main() -> Unit = println(int.to_string(if has_digit("a1b") then 1 else 0))
```

```
$ almide build      # v0.62.0 → Built
$ almide build      # develop  → 2 × error[E0308]
```

Generated Rust:

```rust
let hit: bool = ((&*c >= "0") && (&*c <= "9"));
//                       ^^^ expected `&String`, found `&str`
```

The loop element is now a borrowed `&String`, and the comparison against a `&'static str`
literal is emitted without the conversion.

## Measured

| | this repro | teastia (a ~30 kloc Almide program) |
|---|---|---|
| v0.62.0 | Built | Built |
| `2062dd0c` (first bad) | **2 × E0308** | **2 × E0308** |
| `bcf3316` | 2 × E0308 | 3 × E0308 (see below) |
| `fce3272` (develop head) | 2 × E0308 | 3 × E0308 |

teastia's two failures are the same single source line
([`src/asvs.almd:251`](https://github.com/Aid-On/teastia/blob/develop/src/asvs.almd#L251)),
which is the repro above verbatim.

## Related

`bcf3316` ("Borrow a list forwarded by a wrapper into another module instead of cloning it at
every call") **works** — thank you, it fixed #2164, and I measured the cross-module wrapper going
from 54.55 s to 0.00 s at n=40 000. It adds a third E0308 in teastia of the same class
(a borrowed `String` param assigned to an owned `var String`); that shape already fails on the
released v0.62.0 under a slightly different trigger, so I filed it separately.
