### ISSUE TITLE
native, v0.62.0: a String param assigned to an owned var String fails to compile once the program has a second function

### ISSUE THREAD

**Issue by atzurody** [almide/almide#2189]
## Summary

Assigning a `String` parameter to an owned `var String` fails to compile on native **as soon as the
program contains a second user function**. On its own the same function builds. This is on the
**released v0.62.0**, not only on `develop`.

## Repro

Builds:

```almide
fn keep(lit: String) -> String = {
  var model = ""
  if lit.len() > 0 then {
    model = lit
  } else ()
  model
}

effect fn main() -> Unit = println(keep("openai/gpt-4o"))
```

Does not build — the only change is a second, unrelated function:

```almide
fn has_digit(s: String) -> Bool = {
  var out = false
  for c in string.chars(s) {
    if c == "1" then {
      out = true
    } else ()
  }
  out
}

fn keep(lit: String) -> String = {
  var model = ""
  if lit.len() > 0 then {
    model = lit          // error[E0308]: expected `String`, found `&str`
  } else ()
  model
}

effect fn main() -> Unit = {
  println(int.to_string(if has_digit("a1b") then 1 else 0))
  println(keep("openai/gpt-4o"))
}
```

```rust
let mut model: String = "".to_string();
if (almide_rt_string_len(&*lit) > 0i64) { model = lit; } else { () }
//                                                ^^^ expected `String`, found `&str`
```

`keep`'s parameter is inferred as borrowed once another function is present, but the assignment
into the owned `var` is emitted without `.to_string()`.

## Measured

| program | v0.62.0 | `2062dd0c` | `fce3272` (develop head) |
|---|---|---|---|
| `keep` alone | Built | Built | Built |
| `keep` + one more fn | **1 × E0308** | 3 × E0308 | 3 × E0308 |

## Why it matters

This is the shape at
[`src/providers.almd:35`](https://github.com/Aid-On/teastia/blob/develop/src/providers.almd#L35)
in teastia. It builds on v0.62.0 today only because that parameter happens to be inferred as owned;
on `develop` it is inferred as borrowed and becomes a hard error. So a program can be one unrelated
edit away from not compiling.

Split out of #2188 (a separate native regression bisected to `2062dd0c`) because this one
reproduces on the shipped release.
