### ISSUE TITLE
0.60.0 regression: derived Codec with an `Option[List[Record]] = none` field emits `decode(_v: &Value)` but call sites pass `Value` — `check` green, native `build` fails with E0308

### ISSUE THREAD

**Issue by atzurody** [almide/almide#1713]
## Summary

A derived `Codec` type that has an **`Option[List[Record]] = none`** field generates
`pub fn ..._decode(_v: &Value)`, but the call site for `Type.decode(expr)` still passes a `Value` by value.
`almide check` is green; `almide build` (native) fails in the generated Rust.

**Regression introduced in 0.60.0.** 0.59.2 builds the same source fine; 0.60.0 and 0.61.0 both fail.

This is the "check green must build" class that v0.59.1 was named after.

## Repro

`almide init`, then:

```almide
// src/thing.almd
type Item: Codec = {
  name: String,
}

type Thing: Codec = {
  schema: String,
  extra: Option[List[Item]] = none,
}
```

```almide
// src/main.almd
import self.thing
import json
import fs

effect fn read_thing(file: String) -> Result[thing.Thing, String] = {
  let text = fs.read_text(file) ?? ""
  guard text != "" else err("cannot read " + file)
  match thing.Thing.decode(json.parse(text) ?? value.null()) {
    Ok(t) => ok(t),
    Err(e) => err("bad: " + e),
  }
}

effect fn main() -> Unit = {
  match read_thing("t.json") {
    ok(t) => println(t.schema),
    err(e) => println(e),
  }
}
```

```
$ almide check
No errors found
$ almide build
error[E0308]: mismatched types
    --> <generated.rs>:4778:86
     |
4778 |     match almide_rt_thing_Thing_decode(match almide_rt_json_parse(&*text) { Ok(v) => v, Err(_) => almide_rt_value_null(), }) {
     |                                                                                      ^ expected `&Value`, found `Value`
     |
help: consider borrowing here
```

## What isolates it

Four variants of the same program, only the `Thing` field set changed, everything else identical (0.60.0):

| variant | `Thing` extra field | `almide build` |
|---|---|---|
| A | `inner: Inner` (nested Codec record) | ok |
| B | `items: List[Item]` (list of Codec records) | ok |
| **C** | **`extra: Option[List[Item]] = none`** | **FAIL (E0308)** |
| D | `note: Option[String] = none` | ok |

So it is specifically **`Option[List[Record]]` used as a defaulted field**. Nesting alone, a plain
`List[Record]`, and a scalar `Option` default are all fine.

## Not the `??`

`json.parse(text) ?? value.null()` is not involved — hoisting it to a `let` first fails at the same
place with the same error (`almide_rt_thing_Thing_decode(parsed)`, `expected &Value, found Value`).

## Why this shape is common

`Option[List[T]] = none` is the shape the CHEATSHEET / #1520 / #1563 guidance pushes people to:
`List[record] = []` is documented-unsupported, and `List[String] = []` walls the wasm build
(`__decode_default_list_string` unlinked). So the recommended workaround is now the thing that breaks
the native build in 0.60.0+.

## Versions

| version | `almide check` | `almide build` |
|---|---|---|
| 0.59.2 | ok | **ok** |
| 0.60.0 | ok | **FAIL** |
| 0.61.0 | ok | **FAIL** |

macOS aarch64, prebuilt from `tools/install.sh`.

Found while upgrading a real project (teastia) from 0.59.0; the project is staying on 0.59.2 until this is fixed.

**Comment by O6lvl4** [comment]
Reproduced, root-caused, and fixed in #1719 (A/B-verified: the new native pin fails on the released 0.61.0 binary and passes with the fix).

Root cause: borrow inference runs as a fixed point. A derived decode whose record has an **Option-of-heap** field proves its `&Value` borrow only in round 1 (round 0 runs before the generated option workers' signatures exist). The definition's canonical signature keys update every round, but the **mirror keys** a cross-module call site resolves through (`Thing.decode` et al.) were `or_insert`-frozen at round 0's by-value verdict — so the def emitted `&Value` while your call site kept passing `Value`. Your isolation table matches exactly: `List[Item]` (variant B) proves the borrow in round 0 because the list codec drivers are intrinsic-seeded upfront; every `Option[...heap...]` shape needs round 1 and hit the freeze — the default is not actually required (`Option[List[Item]]` without `= none` reproduces too).

Thanks for the four-variant isolation — it pointed straight at the shape predicate. Labeled `regression`, so it gates the next final release.
